### ISSUE TITLE
Theme not showing in WP updates.

### ISSUE THREAD

**Issue by cupofnestor** [afragen/github-updater#132]
I've re-read the readme, and added a branch (master) and version to my [style.css](https://raw.githubusercontent.com/monadnockMedia/mm_wp_theme/master/style.css).

I've created two theme directories, in one I've placed the above style.css, and in the second I've placed the style.css from the [test theme](https://github.com/afragen/test-child/blob/master/style.css)

I then deactivate, and reactivate gitHub-updater, click "check again"  on the wp-updates page, and still do not see either theme in the update panel.   I'm still missing something.

**Comment by moskeyombus** [comment]
Maybe I've misread this thread, but Bitbucket does in fact support deployment keys.  Log in, go to 'Settings', 'Deployment Keys' is a menu option on the left.  Just discovered this WP plugin today, will dig a little deeper and see if I can get it to work.

**Comment by afragen** [comment]
@moskeyombus my understanding of [Bitbucket Deployment Keys](https://confluence.atlassian.com/display/BITBUCKET/Use+deployment+keys) is that they are SSH keys.

> A deployment key grants read-only access to a public or private repository. With a deployment key a user or a process can pull or clone a repository over SSH.

This plugin and any updating via the WP admin works over HTTP GET or curl not SSH. Because of that Bitbucket-style deployment keys won't work.

Currently all GHU needs is your personal Bitbucket login and you must have `read` access to the repo.

**Comment by afragen** [comment]
If anyone in this issue still has here let's bring it to a new separate issue. Thanks.
