### ISSUE TITLE
Plugin rating

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [afragen/github-updater#163]
Hello! I would like to make a feature request.
I noticed that if the plugin is not in the WordPress repository the rating is set by default to 1 star. 
It would be nice to have an optional header like "Github Plugin Rating" that is used only by the plugins that are not hosted by WordPress. Or at least the rating be set by default to 4.5 or 5 stars.
It makes me cry inside when I see 1 star on the plugin details modal.

**Comment by afragen** [comment]
This is and always has been somewhat arbitrary. Star ratings are based on GitHub stars and forks with negative points for open issues. I have 5 star rated plugins on .org that only have one star here when I'm updating against the develop branch. 

Unfortunately there's just no really good way to rate a plugin on GitHub when there's no rating area.

**Comment by EusebiuOprinoiu** [comment]
I know. That's way I think it would be nice to have an optional header where we can manually set a rating for the plugins hosted only on Github. (Even if it's not a real one)
Obviously, if the plugin is in the WordPress repo it should be ignored.
Yahnis Elsts does something like this with the Plugin Update Checker using a json file.
https://github.com/YahnisElsts/plugin-update-checker

**Comment by JoeHana** [comment]
I would actually suggest that private repos shouldn't display a rating at all. No rating, no fake-rating.

**Comment by afragen** [comment]
I'll look into this. I don't think it should be too hard. Stay tuned.

**Comment by EusebiuOprinoiu** [comment]
No rating for private repos sounds like a good idea.

**Comment by afragen** [comment]
I've got this working for plugins but themes still seem to show a bunch of empty stars. :frowning:

**Comment by EusebiuOprinoiu** [comment]
I haven't used this in a theme yet but I don't think people will miss the rating if you decide to remove it.
After all, if the theme is not in the WordPress repo it's probably a premium one. And as far as I know the rating is displayed only when browsing the official theme directory and not on the theme details page.

**Comment by JoeHana** [comment]
Its actually a matter of avoidable confusion. As you may know some clients are "different" and they maybe feel a bit confused if they see a 0 Star Rating on something they paid much money on. So if possible just remove the rating for everything but just not Plugins/Themes from wp.org repo (since Github & Bitbucket Rating is actually non-existent).

Of course this is not a big deal yet, but if that will be at least on the roadmap for any future version I guess thiss will be much appreceated my some (incl. me)

btw...keep up the good work. I'm still playing around to figure out a few things but after all it seems to me as a great solution. *thumbsup*

**Comment by afragen** [comment]
Try the latest `develop` branch. Star ratings are removed for private repos.

**Comment by EusebiuOprinoiu** [comment]
It works! :)
