### ISSUE TITLE
Getting GitHub Updater Error Code: 403 since upgrading to 4.1.3.5 

### ISSUE THREAD

**Issue by gerrytucker** [afragen/github-updater#172]
Specifically the message "plugin-name was not checked. GitHub Updater Error Code: 403", also "GitHub Updater  was not checked.  GitHub Updater Error Code: 403".

**Comment by afragen** [comment]
You are hitting the GitHub API limit. The limit for unauthenticated checks against the GitHub API is 60 per hour. Each plugin/theme uses about 4 API checks which are cached. 200 and 404 are cached. Nothing else is cached. If you have multiple sites on a shared host, you'll hit this limit sooner. I know I do.

A 403 happens when you have used up the 60 / hour limit. A 401 error happens when either you don't have proper access to a private repo or you've put in an access token to a public repo.

This is really just a notification by the plugin and hopefully it helps me tell users what the problem might be. Nothing to worry about. :wink:

**Comment by afragen** [comment]
Thanks for prompting me to look at these again. I had to change how I stored the error codes as they were getting overwritten. I also add an explanation of code in the README. https://github.com/afragen/github-updater/commit/72861f54b4c0be0611a8ba252647eec047946147

**Comment by afragen** [comment]
Try the latest develop branch. I now include a time until the GitHub API is reset in the error message.
