### ISSUE TITLE
Focus on settings fileds

### ISSUE THREAD

**Issue by szepeviktor** [afragen/github-updater#201]
Could you set focus to the top field on all 3 tabs?

**Comment by afragen** [comment]
I don't know. Does it really matter?

**Comment by afragen** [comment]
Top field in Settings tab may not always be same field as it's dynamically created.

**Comment by szepeviktor** [comment]
The last parameter should be `$arg`, an array.
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Settings.php#L196
That may contain a `focus` boolean.

Now you pass a string and don't use it in the callback.

**Comment by afragen** [comment]
I guess my real question isn't whether it's possible, but why do it at all. To save a single click?

**Comment by jazzsequence** [comment]
@afragen for screen readers maybe?

**Comment by afragen** [comment]
> The last parameter should be $arg, an array.
> https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Settings.php#L196

Fixed and in more places than that. :wink: 

Focus (actually HTML5 `autofocus`) seems to be a boolean to the `input` tag. Since it could only be used once on the page, where would you put it on the Settings tab? Would you really want focus on the Bitbucket username??

I can see using it in the URI field for the Install tabs.

**Comment by szepeviktor** [comment]
It is enough for me to focus on the URI fields.
Thanks.
