### ISSUE TITLE
Theme "Try another version" has sticky branch settings

### ISSUE THREAD

**Issue by aariacarterweir** [afragen/github-updater#258]
PHP 5.3

- I started using branch beta. The dropdown gave me a list of options of all the tags plus "beta".
- I switched to the master branch: beta still showed in the dropdown.
- I deleted the theme and re-installed as master: beta still showed in the dropdown
- I moved the WP install folder, and changed the domain. Now master is showing in the dropdown.
- Changed the theme branch back to beta: now master is showing in the dropdown and not beta.
- Reinstalled theme from beta branch. Master still showing in the dropdown.

Thanks though - not trying to whine! This plugin is awesomesauce!

**Comment by afragen** [comment]
Can you share the URI so I can test?

**Comment by afragen** [comment]
Did you clear the transients by using the Check Again button on the update page?

**Comment by aariacarterweir** [comment]
OMG. That fixed it! TY!!!!

**Comment by afragen** [comment]
Actually, the current branch is pseudo-hardcoded as the first link. This is because some users don't tag releases. To switch/reinstall a different branch you would have to alter the branch header of your theme and likely clear the transients.

Branch switching for themes isn't currently a feature. If really interested please create a new issue with a feature request. Though this will be more difficult for multisite support.
