### ISSUE TITLE
"The plugin does not have a valid header" when trying to activate plugin with Github Installer. WP activates plugin correctly.

### ISSUE THREAD

**Issue by WebSpanner** [afragen/github-updater#281]
When trying to install https://github.com/WebSpanner/ws-schema-tools I get this message after clicking 'Activate' in the Github Installer installation dialog.

However, I am able to activate the plugin afterwards in Wordpress. I can also update the plugin but once again the activation fails.

Is this a problem with my plugin or with git-hub updater? The header in the plugin looks like this:

    <?php
    /*
    Plugin Name: WebSpanner - SchemaTools
    Plugin URI: http://www.makeweb.com.au
    Description: Add schema.org microdata to your wordpress site using shortcodes.
    Author: Andrew Feeney
    Version: 0.2.2
    Author URI: http://www.makeweb.com.au
    GitHub Plugin URI: https://github.com/WebSpanner/ws-schema-tools
    GitHub Branch: master
    */

**Comment by afragen** [comment]
I think that's an error on my end. I don't create the `Activate Plugin` button but I can see that it's not passed the plugin info to work correctly.

I'll have to dissect it a bit. Thanks for bringing this to my attention.

**Comment by WebSpanner** [comment]
No worries, hope you can find the issue without too much trouble!

**Comment by afragen** [comment]
OK, problem can be fixed but only by removing the activation link. You'll have to activate the plugin from the plugins page. 

The reason is that when installing I have no way to capture the plugin file name as it's not entered anywhere. It is required for activation, that's why you get the error.

I've found a solution to remove the link. Not a great solution, but a less confusing one. Sorry but it's just not feasible to fix so it works.

**Comment by afragen** [comment]
Fixed in `develop` branch.
