### ISSUE TITLE
Themes and plugins will not work with accounts with two-step authentication

### ISSUE THREAD

**Issue by linuxbastard** [afragen/github-updater#322]
I've got two-step authentication turned on for my account on bitbucket and when I use it to install a theme or plugin I get the "FORBIDDEN" error message. Turning off two-step authentication sort "fixes" it, but I'm wondering if I'm missing a step or if there was anything I should be doing to be able to use it with accounts with two-step authentication?

I have a team with individual accounts working on various parts of a theme and we use a separate account to sync everything to our sites, that account has two-step turned on.

**Comment by afragen** [comment]
Unfortunately, I haven't been able to figure out how to enable oAuth authentication to the plugin. It only works using Basic Auth. Sorry, but it is on my radar as someone to add.

**Comment by afragen** [comment]
It's apparently on Bitbucket's radar to provide application specific token like GitHub. That should end up as the simplest solution.

https://bitbucket.org/site/master/issues/11774/application-specific-passwords-or-tokensApplication%20specific%20passwords

**Comment by lykken** [comment]
Hi, @afragen! Cool plugin. 

Does the personal token obtained for GitHub Enterprise work when set up with two-step authentication? I receive the following error at the top of the plugin page after installing a plugin with GitHub Updater: 
```
Plugin Name was not checked. GitHub Updater Error Code: 401	
There is probably an error on the GitHub Updater Settings page.
```

The plugin is installed correctly, so to me it seems like this happens when the plugin is looking for updates. I'm not sure if I am doing something wrong or if it's just not supported ;)

**Comment by afragen** [comment]
Two step authentication is not supported.
