### ISSUE TITLE
Github updater renames my plugins folder and turns off the plugin, updating never works

### ISSUE THREAD

**Issue by mvaneijgen** [afragen/github-updater#333]
I have my plugin on a public repo on Github (https://github.com/StudioAlloy/studio-alloy-essentials) and update my releases, but the update never works. When I hit update the spinner in Wordpress keeps loading and never finishes an when I check my plugins folder my plugins folder is renamed with some random hash after it and the plugin is turned off. 

Is there something I am missing? Is there a complete guide how to work with this plugin?

**Comment by flashadvocate** [comment]
How are you updating? Are you using "check for updates -- check again"
through the dashboard > updates page?

The hash isn't random, that's the commit hash the repo was pulled at.

**Comment by flashadvocate** [comment]
Also, the Readme is pretty thorough.
https://github.com/afragen/github-updater/blob/develop/README.md#usage

**Comment by mvaneijgen** [comment]
@flashadvocate though the dashboard that is where the spinner keeps loading.

**Comment by mvaneijgen** [comment]
Still no luck, it will also revert back to the first version in the repo and turns it self off. my plugin is called `repo-name` and after updating it is called `company-account-plugin-name-some-hash` is there a step by step guide I can follow to fix this issue?

**Comment by flashadvocate** [comment]
@afragen I'm noticing that, at the least, GHU seems to be disabling itself for no apparent reason

**Comment by afragen** [comment]
Is everyone using the current version?

When do you notice it disabling itself? This used to happen with an update from the plugins page, but shouldn't any more.

**Comment by afragen** [comment]
@mvaneijgen I'll try to test using your plugin and see what I get.

**Comment by afragen** [comment]
@mvaneijgen here's the problem. You're tagging your releases and GHU picks the highest sorted tag to create the download link. Your highest sorted tag is `0.51 > 0.6.3`. GHU sees `0.6.3` as your remote version and `version_compare()` sees `0.6.3 > 0.51` and shows an update. The update takes the 0.51 tag and installs it. Please remove the `0.51` tag.

Additionally, v051 has the following header
`Github Plugin URI: https://github.com/StudioAlloy/alloy-basic-settings-wp`

This will not point to your repo and therefore no further updating will happen.

Let me know if there are further issues after deleting this tag.

**Comment by afragen** [comment]
@flashadvocate under what circumstances?

**Comment by mvaneijgen** [comment]
Hey, @afragen thanks. 

I have removed the `0.51` and reinstalled the plugin though the `Github updater backend`, and have released a test version `0.6.3` and have `0.6.2`installed, but it will now not prompt me that there is an update.

**Comment by afragen** [comment]
Use the Check Again button to clear the transients.

**Comment by mvaneijgen** [comment]
@afragen where is tis `check again` button? Cause I don't see in the `/plugins.php` nor in the `Github updater settings` pages.

**Comment by flashadvocate** [comment]
@mvaneijgen it's on the Dashboard > Updates page

@afragen I can't seem to nail down a specific circumstance where the plugin deactivates, but it definitely happened in between 5.3.0 and 5.3.1

**Comment by afragen** [comment]
@flashadvocate can you check to see that GHU's directory is correctly named? Also, to test you could use the branch switching to reload your current branch and see if the plugin successfully reactivates. Make sure you stay on that page until it's completed.

**Comment by afragen** [comment]
@mvaneijgen in my testing your repo now appears to update correctly.

**Comment by ethanclevenger91** [comment]
_Probably_ related, but not getting consistent results. Updating from the Updates screen (not AJAX) on a bunch of sites this morning from 5.2 to 5.3.1 - Either GitHub Updater plugin directory is getting renamed with your name and the hash (40% of the time), I'm getting a "forbidden" error when trying to update (20%), or things go smoothly (40%).

Not great debugging information, but wanted to confirm I was also running into this issue.

**Comment by flashadvocate** [comment]
I ran into it on a site running 5.3.0 today

![screenshot_3](https://cloud.githubusercontent.com/assets/7848492/11754212/b1eaf75e-a017-11e5-9bbe-ffa3265634b5.png)

**Comment by afragen** [comment]
Clearly that's an issue where the renaming code didn't process. Can you provide any details on the server?

Can you try using the branch switcher to reinstall the current branch and see if the updating still has an issue?

**Comment by afragen** [comment]
@flashadvocate this is clearly a different issue. The reason that renaming is giving you these specific results is because the plugin directory wasn't correctly renamed when you initially downloaded it from GitHub and installed it. Here's what happens.

1. The plugin directory is initially downloaded from GitHub and named `github-updater-master`, as you downloaded the master branch.
2. The renaming code doesn't identify this as correct because the plugin pulls the correct repo name from the plugin's headers. This obviously for already installed plugins.
3. Because there is no identification of the correct plugin name the directory gets renamed to the commit hash name of the update download. `afragen-github-updater-469ce78`
4. If the plugin directory is already named for the hash it may subsequently get correctly renamed somewhat accidentally.

This probably happens enough that I should include the fix I just pushed to the `develop` branch. If you want you can test but it would seem that over time. Once you correctly upgrade GHU to the next version the problem should fix itself.

Thanks for the report is a very confusing issue to test and if you didn't include the screenshot above I never would have thought of that.

**Comment by afragen** [comment]
If there are similar issues still happening please post back here. Thanks.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/commit/99dfbf812b70949f92e6f65546144899580d8435 fixes
