### ISSUE TITLE
Themes (or plugins) that have composer dependencies

### ISSUE THREAD

**Issue by dangreenisrael** [afragen/github-updater#407]
I've been developing a [theme](https://github.com/dangreenisrael/agency-blog) that has composer dependencies.

When I install it using this plugin, the dependencies don't get updated and thus the theme doesn't work.

Is there a way to do this that I'm missing, or should I get working on it myself?

**Comment by afragen** [comment]
There's a way to do it, but you will need to create a **release asset**. Normally, GitHub Updater essentially treats the GitHub repo just like the .org repo. The plugin/theme must be fully built.

I have included an option so that by adding the header `Release Asset: true` and creating a release asset in the following naming convention `<repo>-<tag>.zip`, the fully built release asset will be used for updating.

Please refer to https://github.com/afragen/github-updater#release-assets

Let me know if you have further questions.

**Comment by dangreenisrael** [comment]
Thats awesome thanks
