### ISSUE TITLE
Bug when prefixing "v" to tag name

### ISSUE THREAD

**Issue by curtisbelt** [afragen/github-updater#416]
Here's the scenario: I have a theme repository with following tags:

* v1.0.0
* v1.0.1
* 1.0.2   <-- no v on this tag
* v1.0.3
* v1.0.4
* v1.0.5
* v1.0.6

On the server, I am running version 1.0.5.

The 1.0.6 update is showing as available. Okay - I start the update. But it "updates" me to 1.0.2. I can see it in download URL, 1.0.2 is specified.

I noticed 1.0.2 is the latest version without a "v" in the tag name.

So I re-name "v1.0.6" to "1.0.6", and after waiting and using "Check Again" it detects the new tag name and successful updates to 1.0.6.

Here's an additional related bug: When I was on v1.0.5 (and 1.0.6 wasn't pushed yet) on the Network Themes page, where it says "Theme is up-to-date! Rollback to:", it's options were v1.0.4, v1.0.3, v1.0.1. it skipped 1.0.2. Looks like same bug but in reverse?

Before I figured out how to work around this by not including the "v", I was using branch switching and re-applying the master branch, which retrieved the head of master branch.

**Comment by afragen** [comment]
So here's the problem. `v1.0.x` is not real semantic versioning and `version_compare()` doesn't treat it the same way nor does sorting an array behave the same.

What happens is that `1.0.2` sorts as newer than `v1.0.x` and the newest tag is installed. Additionally the newest tag doesn't rollback as that's the one installed.

Unless you follow real [Semantic Versioning](http://semver.org) you'll have issues.

**Comment by curtisbelt** [comment]
I follow Semantic Versioning for the actual version number but this was the name of the tag. If you're interpreting the tag the same way that is fine and I can follow that convention, however it still leaves the rollbacks in question - only non-semantic versions showed up there.

**Comment by afragen** [comment]
GHU doesn't make a distinction. The GitHub API pulls the tags by what you put there and that's how I store the tags in the theme object in GHU.

For the rollback, I take the 4 highest sorting tags and pop the highest off the top returning the 3 remaining. So in your case your highest 4 tags would be ( 1.0.2, v1.0.6, v1.0.5, v1.0.4 ) popping the highest off the top (because that's the one that you currently have installed) leaves only the rollbacks with a leading **v**.

Make sense?

Short answer is semantic versioning should be used everywhere a  version number is utilized. This is really only in 2 locations, the actual version number in the plugin/theme header and in the tag.

**Comment by curtisbelt** [comment]
Understood! Thank you sir.
