### ISSUE TITLE
Keeps forcing folder name

### ISSUE THREAD

**Issue by cvladan** [afragen/github-updater#461]
I am successfully using plugin to update plugins & theme from my private repositories on BitBucket to multiple sites.

But I have a problem which is a bug probably. On update procedure, Github-Updater keeps installing in a folder that is __named same as repository__. And I want my folder to be different than repository slug.

Any solution?

**Comment by afragen** [comment]
This is by design as this is "the WordPress way". 

I do have a setting for using extended naming, you can find it in the readme and on the Settings page. It only works with plugins, as themes don't seem to load otherwise. I creates the naming pattern `github-afragen-plugin_slug` or in your case `bitbucket-cvladan-plugin_slug`.

**Comment by cvladan** [comment]
Are you sure? I am not talking about initial folder naming - that I understand.

But after I installed plugin/theme, and then rename its folder, it should update in that folder normally and not recreate a new one.

You also wrote in project README:
> When initially adding a theme, the directory must be identical to the repo name.

That suggests that afterwards, it is possible to rename that folder to be different than repo-name.

**Comment by cvladan** [comment]
I'm sorry, but I just want to be clear that you understood question properly.

**Comment by afragen** [comment]
No, unfortunately that is how I designed the plugin. 

Since GitHub and all the others services name downloads based on a format of something like `owner-repo-hash|branch`, I have to use the renaming code for every update. 

There would be no easy way to allow for essentially random naming. Even while random naming works with plugins, it doesn't seem to work with themes.

**Comment by cvladan** [comment]
OK. Thanks ;)
