### ISSUE TITLE
Support language packs

### ISSUE THREAD

**Issue by grappler** [afragen/github-updater#50]
At one point theme and plugin authors will be able to update translations separately to the code from WordPress.org.

I think the structure is there to do so. I would be interested if github-updater could do it. The way I see it if I update the translations branch then the translations get updated.

http://ottopress.com/2013/language-packs-101-prepwork/

Just an idea.

**Comment by EusebiuOprinoiu** [comment]
Language packs can be loaded using load_textdomain(), load_plugin_textdomain() or load_theme_textdomain().
The first function can be used to load the language file from any location while the other two are usually used to load the language file stored within the plugin or theme. Since WordPress loads the first file it finds all you need to do is to try and load it from the wp-content/languages/ folder first. And if none is found, load it from the plugin as usual.

Here is an example: http://eusb.me/21Qiu8E

**Comment by benoitchantre** [comment]
I think that language packs only work with code hosted on wordpress.org

**Comment by afragen** [comment]
I'm closing this issue in favor of #440
