### ISSUE TITLE
Trying to change branches on plugin is showing "tag rollback" message

### ISSUE THREAD

**Issue by joelworsham** [afragen/github-updater#519]
I have a plugin on a website that is hosted on GitHub. It's worked fine previously for branch switching, but lately, rather than showing available branches to switch to, it shows the "No previous tags to roll back to." message.

![](http://d.pr/i/OmWb+)

**Comment by joelworsham** [comment]
Other Notes:

- This happens on ALL of our GitHub-hosted plugins on this website.
- The theme is working just fine for branch-switching and updating.
- New tagged versions do show up and update without fail on the live site (the site I'm referencing in this issue is a staging site version)

**Comment by afragen** [comment]
What version and branch are you using?

**Comment by joelworsham** [comment]
Branch: develop
Version: 6.1.1.12

Another Note: I manually pushed the `develop` branch for that plugin, and now that plugin (and that plugin only) is working.

![](http://d.pr/i/mm4S+)

**Comment by joelworsham** [comment]
Those screenshots just showed me the issue. We had made a push via SFTP and typed the branch name out. It appears the branch name was incorrect. Previously, we had it on branch `issue/20/errant-buttons`, but the actual branch on GH is `issue/20/errant-button`. Of course, the system failed in an odd way by not showing any branches/tags available.

**Comment by afragen** [comment]
Does that mean this issue should be closed?

**Comment by joelworsham** [comment]
Wellllll yes and no. The root cause was my fault, but the end result was odd. It seems that if the current branch is inaccurate, there should be a message about it. And should probably be able to still change branches

**Comment by afragen** [comment]
I think we're into the issue with #520 where extended naming is causing the problem.

**Comment by joelworsham** [comment]
Okay, well I suppose I can close this then!

**Comment by CurtisBelt** [comment]
@afragen 

I had this exact problem today ("No previous tags to roll back to.").

The problem was that I had forgotten to rename the branch name to 'master' after doing some merges. The branch name used on the theme was deleted from origin and therefore did not exist.

By manually SSH'ing into server and updating style.css, changing branch name to 'master', I was able to restore the branch functionality and proceed with my theme update.

I then realized I would have to do this to multiple sites which used my theme. So to speed this up, I tried just creating a new branch with the same name as the one which is missing. That worked, and then I deleted the branch after I set all of the themes back to master branch.

Just wanted to let you know this bug still exists.

**Comment by afragen** [comment]
@CurtisBelt unfortunately this is a workflow issue and not directly related to GitHub Updater.

If I understand correctly. You have a theme installed with a GitHub Branch header that no longer exists because it was deleted after being merged.

It must be that the because the initial check of the API for the referenced branch doesn't exist there is no fallback to the master branch. You have found creative solutions to solve this problem.

I would try to keep the non-testing site that use the development/testing branch of your project to a minimum so that most sites are on the master branch. Sorry, but I just feel this is a workflow issue and not a software issue.

**Comment by afragen** [comment]
I think I can at least add a _broken_ indicator to the Settings page so that any issue can be narrowed down. It won't solve this issue but should make it more obvious. https://github.com/afragen/github-updater/commit/e00af5875f70cb966f5fdd8eecad5b0ad411ed65
