### ISSUE TITLE
Can't use same name for plugin and theme

### ISSUE THREAD

**Issue by greghaygood** [afragen/github-updater#544]
I'm building a site that has a separate custom plugin and theme using the same name (e.g. client code). It appears that GHU uses the base repo directory as the key because it only shows one of them in the admin panel, and looking in the options table seems to confirm that. I enabled Extended Naming and so the plugin has a different folder name, yet I still only see the theme's entry in the dashboard.

It wouldn't be so bad if it were still refreshing both repos, but while it shows me the Theme version in the dashboard, it only seems to pick up remote repo changes from the plugin version.

Am I missing something to allow GHU to support this setup, or do the repo root folders need to be different?

(Awesome plugin, BTW!)

**Comment by afragen** [comment]
Each repository must be unique. The slug is taken from the repository directory. I'm not even sure how you could have duplicates unless there are 2 separate owners. Can you share examples of the repository URLs?

Extended naming is really present in case there's a plugin in dot org with the same slug.

**Comment by greghaygood** [comment]
Here's example URLs for what I'm doing:

https://gitlab.com/my-client-themes/project-code
https://gitlab.com/my-client-plugins/project-code

The plugin is used for the API bits, hence I didn't want in the theme. And the theme is (duh) the front-end code that serves the WP pages and the React app that talks to the API. Normally these would be in the same repo/namespace and deployed via another mechanism, but I used this approach for my current project to align with GHU's model.

It seems like I could just tweak it to be more like:

https://gitlab.com/my-client-themes/project-code
https://gitlab.com/my-client-plugins/project-code-app

And bypass this constraint. Is that what you would recommend? It might be nice to have a little mention in the README about it, since it isn't clear when using GHU that it requires that.

Thanks!

**Comment by afragen** [comment]
I added something to the Usage instructions here, https://github.com/afragen/github-updater/wiki/Usage

I would recommend appending `-theme` to the theme's slug or possible adding `-api` To the plugin component.

 Remember renaming the slug will require renaming the git repo.

Fundamentally GitHub Updater strives to behave and work under the same constraints as the plugin/theme directories. Unique slugs all around. The extended naming option for plugins was in case _your_ plugin repo was identical to an existing dot org plugin.

Your examples of having different repo owners so that you can name the repositories the same is interesting and the source of these issues.

Fundamentally the owner of the repo isn't used as a differentiator for the repository.

Make sense?

**Comment by greghaygood** [comment]
Yep, all good. Thanks!
