### ISSUE TITLE
Having update errors when repo-name contains a dot

### ISSUE THREAD

**Issue by stkjj** [afragen/github-updater#595]
One of your themes (owncloud/2017owncloud.org) refused to update. Looking at the download-URL stated in execution we found out that anything from behind the dot was trunkated, e.g. the plugin tried to update owncloud/2017owncloud, which indeed does not exist.

We made a workaround be eliminating the dot in the naming, but as this a valid name, we would love to have the opportunity back again.

**Comment by afragen** [comment]
This is intentional and likely will not be changed. This issue is that _traditionally_ filenames have extensions and these extensions are not typically part of the actual filename. A common issue I was having was people would add a header similar to `GitHub Plugin URI: https://github.com/owner/myrepo.git`. I have to trim the extension for the code to correctly process. 

My recommendation would be to change the repository name to `2017owncloud-org` or similar as this will work as expected.

I use `pathinfo()` to determine this information and use the `filename` output. https://github.com/afragen/github-updater/blob/13d2ae13c059312e45ec0965ae1604bb512cf31c/src/GitHub_Updater/Base.php#L855

**Comment by afragen** [comment]
It seems you have found the solution, https://github.com/owncloud/2017owncloudorg/blob/master/style.css
