### ISSUE TITLE
"No previous tags to rollback to." when clicking "try another version"

### ISSUE THREAD

**Issue by yaronguez** [afragen/github-updater#620]
All of my GitHub Updater enabled plugins say that they're on the master version even though they're on an alpha version. This happened suddenly today and clear the GitHub Updater cache or WP Engine cache doesn't resolve it. When clicking "try another version" to manually select the alpha branch I get the notice "no previous tags to rollback to". This doesn't happen on the GitHub Updater plugin itself which does in fact let me choose other versions, none of which are able to resolve this particular issue. All of the effected plugins are on Bitbucket and password protected.

**Comment by afragen** [comment]
Did you recently upgrade to a newer version of GHU? What does the Bitbucket Settings screenshot look like?

**Comment by yaronguez** [comment]
I'm not sure when we upgraded but we're using the latest version. All of the repos in the BitBucket settings have an exclamation point next to them for some reason. Plugin updates are no longer showing up either.

**Comment by afragen** [comment]
When I updated to v7.0.0, all the branch switching changed and you would've needed to use the branch switcher to re-install your non-master branches so that the database would collect the branch information.

I recently added background updating via WP-Cron and it seems to be problematic for some. It will only begin the updates when wp-cron.php runs. You can force this by one of the following 3 methods. 

1. Open `http://mysite.com/wp-cron.php` in another browser window ( least reliable )
2. Use WP-CLI and run `wp cron event run --due-now`
3. Add the filter, `add_filter( 'github_updater_disable_wpcron', '__return_true' );` to revert back to the old foreground updating.

The red exclamation icon simply means that the main repo file hasn't had it's data returned and properly stored in the cache.

**Comment by yaronguez** [comment]
Thanks for the troubleshooting help,  Andy. I'm on WP Engine so no CLI,
unfortunately. Hitting wp-cron.php manually resolved the issue for one
plugin update before it returned. Another odd issue encounting is where all
branch information disappears entirely in the plugin list. When this
happens it seems that the BitBucket tab in GitHub settings also disappears.
At that point I added the filter and it seems to have resolved the problem.
Thanks again for your help and let me know if I can help you troubleshoot
it further.

**Comment by afragen** [comment]
Can you let me know what plugins you have installed, including my-plugins?

**Comment by joshsmith01** [comment]
I had this issue as well. Basically, all the plugins that I installed with GHU had the red exclamation point. I'd constantly refresh cache and sometimes some of the exclamation points would change to the padlock. Then they'd go back to the exclamation point. 

@yaronguez , I'm also on WP Engine and I do have access to the CLI. It's under the Advanced tab. I had to ask for it, specifically. You may be able to get that. Regardless, I ran the `wp cron event run --due-now` command and all is well now.

**Comment by afragen** [comment]
@joshsmith01 constantly hitting the refresh will only continue the issue. The reason that the red exclamation icon is present is because the API check, scheduled as a WP-Cron event, hasn’t yet run.

If this is a persistent issue you might look to disabling WP-Cron and setting up a real cron job via cPanel. You should use that WP-CLI command.

**Comment by afragen** [comment]
https://github.com/afragen/github-updater/wiki/Background-Processing
