### ISSUE TITLE
Why can't I activate plugin after I install it with github-updater?

### ISSUE THREAD

**Issue by ivan133** [afragen/github-updater#636]
http://awesomescreenshot.com/0ea6er612c

Is it by design or is it something wrong with my plugin?

**Comment by afragen** [comment]
Nothing wrong with your plugin. This is by design. As this function enables the user to install plugins from virtually anywhere I didn’t want the support issues of having a poorly written plugin be activated from within GHU and white screening someone’s site. If you have to return to the Plugins page to activate the plugin no one will assume it has anything to do with GHU.

You can use WP-CLI to install and activate in one step.
