### ISSUE TITLE
After updating the plugin, rollback to the old version of the plugin

### ISSUE THREAD

**Issue by AntonAnastasiia** [afragen/github-updater#652]
When installing the plugin from the repository Bitbucket, a new plugin is installed. I noticed that the name of the directory and the plugin file is different. Rename the file, now the name of the directory and name file of the plugin match. Re-installed the plugin from the repository Bitbucket and reduced its version to see which version to update the plugin and it was again updated to the old version. Maybe it's related to Plugin name? 
Even before installing the plugin on the site, its name was Plugin Name: Content Project, after changed the name to Plugin Name: Post PROST. Again, when you install the plugin with Github Updater installed the latest version plugin, but when you update, a very old version with the name Plugin Name: Content Project is returned.

**Comment by afragen** [comment]
If you install the plugin from the Install tab in GitHub Updater the naming of the folder should be correct.

It seems there are differences in the plugin’s headers that are causing this plugin name change. Nothing in GitHub Updater changes content inside of any file.

**Comment by AntonAnastasiia** [comment]
Thanks for the answer. 
In the screenshots I'll show you what I get
1. I install my plugin through GitHub Updater
https://prnt.sc/ii4ze3
2. Change the version of the plugin https://prnt.sc/ii4yrd
3. Update appeared https://prnt.sc/ii501n 
I click and ...
4.   I get the old version of the plugin.
 https://prnt.sc/ii5096
5. Refreshing the page https://prnt.sc/ii50f6  that is, I get the plugin version 2017-09-01 https://prnt.sc/ii50xa
I can not understand why. 
Directory slugs and plugin slugs identical. http://prntscr.com/ii578f

**Comment by afragen** [comment]
This is what I think is happening. You have installed the `master` branch of the plugin. You have updated the plugin and GitHub Updater correctly identifies that an update is available. When you update it _updates_ to a lower version number.

My guess is that you are behind on tagging your releases. If you tag releases you must continue this process otherwise GHU will use the most recent tag for updating even if that is not the most current version.

https://github.com/afragen/github-updater/wiki/Versions-and-Branches#tagging

**Comment by AntonAnastasiia** [comment]
Thank you! In fact, everything is as you wrote. 
https://prnt.sc/iimgbk
https://prnt.sc/iimgh2
