### ISSUE TITLE
Plugin file does not exist

### ISSUE THREAD

**Issue by HeadStudios** [afragen/github-updater#705]
After installing the zip I downloaded as a plugin through the upload method in Wordpress I get the following error:

The plugin github-updater-8.2.1/github-updater.php has been deactivated due to an error: Plugin file does not exist.

Any idea on why this is?

**Comment by afragen** [comment]
My guess is that you are seeing this because you downloaded and installed the zip file from GitHub without renaming it. Recently I have put in code to correctly rename the plugin on activation. As such, once the renaming occurs you will see a notice that the plugins file doesn’t exist.

Look in your plugins page. I’m betting it’s there ready to be activated.

Let me know if it’s something different.

**Comment by afragen** [comment]
I see where there might be an issue. I didn’t test to see what would happen if a download was from the releases. I’ll check it out. Thanks for the report.

**Comment by afragen** [comment]
This is from v8.1.0.
https://github.com/afragen/github-updater/commit/18a8a6616a8826add901cf2edec75269ec17e4b3#diff-8b1c3fd0d4a6765c16dfd18509182f9d
