### ISSUE TITLE
Issue with Release Assets?

### ISSUE THREAD

**Issue by thefrosty** [afragen/github-updater#712]
According to the [docs](https://github.com/afragen/github-updater/wiki/Settings#release-assets) the Release Assets header should pull from the release. Is this the case for fresh installs from the "Install Plugin" tab?

Specifically testing this with [cedaro/satispress](https://github.com/cedaro/satispress/issues/76) and I am setting the master zipball being used to install `https://api.github.com/repos/cedaro/satispress/zipball/master` when entering the details on that install tab. 

Is there something I am missing?

**Comment by afragen** [comment]
Unfortunately using the release asset doesn’t work from the Install Plugin tab. The reason is that the Install tab has no knowledge of any of the headers. 

There might be some other mechanism to install a plugin from a URL but that’s not how this works here. 

Sorry. 

The only way to use GHU’s Install is to immediately edit the main plugin file to decrease the version number and then update to the release asset.

**Comment by afragen** [comment]
@thefrosty I think you’re gonna like what’s coming to develop.

**Comment by thefrosty** [comment]
👀

**Comment by afragen** [comment]
@thefrosty I'm not saying how to use it, I want to know how intuitive or what I need to put in the wiki.

**Comment by thefrosty** [comment]
I'll try thing out and get back to you.
