### ISSUE TITLE
"Enable Branch Switching" shows incorrect 'current branch' message

### ISSUE THREAD

**Issue by erikmolenaarnl** [afragen/github-updater#733]
Hi @afragen! When "Enable Branch Switching" is on, I noticed plugins installed from WP.org incorrectly show that a current master branch is installed. This is kinda confusing. Please note: the override is off.

Maybe this is done intentionally but got me confused a bit so I thought I might add it as an issue. Thanks!

![2018-11-09_16-45-34](https://user-images.githubusercontent.com/22014267/48273243-c3ded280-e440-11e8-8886-5ea3811ddc0c.jpg)

**Comment by afragen** [comment]
This is intentional. When branch switching is enabled and the plugin has the appropriate header for working with GHU the default branch of `master` is shown. The way to set a different branch is to install a different branch from the Install tab or use the branch switching to switch to a different branch.

I need to keep testing but, the new override filter should behave the same as the previous default where if on `master` branch dot org updates take precedence.

**Comment by afragen** [comment]
Regrettably this example doesn’t seem to use a consistent branch pattern for developing. It’s OK but it means that some data will appear odd. 

This plugin is developing in the `master` branch and doesn’t keep a branch with the current release.
