### ISSUE TITLE
Refresh Cache - Check for updates slow /inconsistent to start

### ISSUE THREAD

**Issue by sagescrub** [afragen/github-updater#753]
I have been using this plugin for some time now and am very happy with its function. The only bothersome point is when I am ready to download an update, I understand I must click the "refresh caches" button. When I do this it takes a long time to finally display the message "Please be patient while WP-Cron finishes making API calls." Once that message displays, the plugin consistently and efficiently downloads updates. However, the thing is that message does not appear right away after clicking the "refresh cache" button. Sometimes I have to press that button several times and walk away for a while and then come back and refresh the page. It seems that refreshing the page has something to do with triggering the "Please be patient while WP-Cron finishes making API calls." message to appear. I am not sure.

**Comment by afragen** [comment]
When you refresh the cache the API’s must be queried again. This happens in the background via WP-Cron, which is why the notice appears. 

The caches automatically expire after 12 hours. Under normal circumstances the update notices should show without having to refresh the cache. You also shouldn’t need to refresh the cache multiple times in a row.

Sometimes you might need to reload the page or go to another page until WP-Cron fires.

**Comment by afragen** [comment]
I'm trying the call to `wp_cron()` directly after refreshing the cache. But wp-cron avoids race conditions so it might not run immediately after clearing the cache.

**Comment by afragen** [comment]
The message shows after wp-cron.php is run. If the message doesn't show it's possible that all the updating was done in the background while you were on other pages.

If you want don't want background updating you can add the following filter to bypass it.

```php
add_filter( 'github_updater_disable_wpcron', '__return_true' );
```

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by sagescrub** [comment]
Thank you I will give that a try and see what happens :)
