### ISSUE TITLE
Case where the information about the repositories disappear

### ISSUE THREAD

**Issue by jordymeow** [afragen/github-updater#762]
First, I installed a plugin through BitBucket. Everything worked fine. Then I installed a second plugin through BitBucket. Everything disappears. Nothing was shown anymore in GitHub Updater, even the first plugin disappeared.

I don't know why it happened, but I made a mistake with the second plugin: it didn't have the Bitbucket Plugin URI. So I understand it wouldn't be added to the repositories, but it shouldn't affect anything else, of course :)

I added the Bitbucket Plugin URI to the second plugin, and I had to reinstall both plugins through GitHub Updater and now it works.

Another thing (not sure if I should open a new thread for that). Why do we have to use the filter github_updater_override_dot_org to avoid the plugins to get their updates through the WordPress Repository? Since I installed those plugins through GitHub Updater, I expect that the updates would go through my own repositories. 

Thanks a lot :)

**Comment by afragen** [comment]
You should only need to use the override filter if a plugin with the identical slug exists on in the w.org directory.

So, because GHU uses background updating the update process doesn’t start until wp-cron is run. You should see a notice about that. Once wp-cron has run the tabs in GitHub Updater Settings for the different git hosts should be visible again. It will likely happen every 12 hours or when you Refresh Cache.

It can be a little disconcerting but it’s purely cosmetic.

https://github.com/afragen/github-updater/wiki/Background-Processing

**Comment by jordymeow** [comment]
Ok, I didn't encounter any other issues, so maybe I wasn't patient enough last time :) I will close this. And thanks a lot for your help, this plugin is fantastic.
