### ISSUE TITLE
GitHub Updater Error Code: There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue. 

### ISSUE THREAD

**Issue by pcoweb** [afragen/github-updater#789]
I am trying to understand the reason for this error. I have downloaded and activated:
Downloaded GitHub Updater Support Plugin
[Dependency] WP Debugging has been installed and activated.
[Dependency] The Debug Bar plugin is required

I have just one plugin that needs the GitHub Updater
Contact Form DB

I am not sure what to look for after activating the plugins.
I have visited the URL https://mysite.com/wp-cron.php
Also, not knowing for sure, from a command prompt I ran >php wp-cron.php
The error message remains.

**Comment by afragen** [comment]
So firstly, you actually have 2 plugins that need GitHub Updater, one is GHU itself.

Activating the support plugin will stop the background updating. I prefer using Query Monitor, but looking at the HTTP Requests will show if there is an error.

That particular admin notice simply notes that it has been more than 24 hours since wp-cron.php was last run. Often it will show when no one has been to the site in over a day. Often simply refreshing the page should be enough to get wp-cron.php to run. Some hosts disable WP Cron and this helps to identify that.

If you have WP-CLI installed, running `wp cron event run --due-now` should run all due wp cron events.

**Comment by pcoweb** [comment]
Thank you. Yes, of course I forgot about GHU.

Indeed there was some issue with cron running. After I ran via command line 'wp cron event run --due-now' The issue disappeared. Also it resolved another issue with a different plugin where some expired entries were cleared from a table and so that started working correctly. That issue had existed for several days and i was just starting to troubleshoot.

I was running Query Monitor.... I can deactivate the other debugging plugins. I also installed the crontrol plugin so that I can monitor if cron is running. WP logs a couple hundred visitors per day so I will do more investigating with dreamhost to make sure that they are not blocking something.

Thanks for your help, because I think that your error message helped me find that there is an issue with my cron. It is not disabled in wp-config.php.

**Comment by afragen** [comment]
Debugging wp-cron issues are tough. It's the primary reason I created that notice in the first place.

Yes, feel free to deactivate the other debugging plugins. 

You're very welcome. I'm glad it also pointed you in the direction of solving other issues.
